# Generated by Django 3.1 on 2022-04-18 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Large',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.CharField(blank=True, max_length=50, verbose_name='目的')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Middle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle', models.CharField(blank=True, max_length=50, verbose_name='目標')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_large', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_middle', to='api.large', verbose_name='対象の目的')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=50, verbose_name='タスク')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_middle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_task', to='api.middle', verbose_name='対象の目標')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
